---
title: "Module 2: Digitalisation in Research" 
subtitle: "Data management practices and platforms for sharing data"
author: "Hannah Metzler <br> *CSH Vienna & Medical University of Vienna*"
date: "26.11.2021"
output:
  xaringan::moon_reader:
  #  seal: false # this hides the title slide to make a costum one below
    lib_dir: libs 
    css: [xaringan-themer.css, "libs/footer&middle.css"]
    nature:
      beforeInit: ["libs/perc.js"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
# #This block contains the theme configuration for the CSS lab slides style
library(xaringanthemer) #
library(showtext)
style_mono_accent(
  base_color = "#1f5c99",
  text_font_size = "1.5rem",
  header_font_google = google_font("Raleway"),#("Yanone Kaffeesatz"),
  text_font_google   = google_font("Arial", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

layout: true

---

# What is data management?


---

# Platforms

* [Open Science Framework](osf.io)
* [Zenodo](zenodo.org)
* Figshare

---

# Things to mention

* DMP Tool
* DOIs